base/api/urls.py
from . import views
from django.urls import path
urlpatterns = [
    path('', views.getRoutes),
    path('rooms/', views.getRooms),
    path('rooms/<int:room_id>/', views.getRoom),
]

base/urls.py
from django.urls import path
from . import views
app_name = 'base'
urlpatterns = [
    path("", views.home, name="home"),
    path('login/', views.loginUser, name='login'),
    path('register/', views.registerUser, name='register'),
    path('logout/', views.logoutUser, name='logout'),
    path("room/<int:room_id>", views.room, name='room'),
    path("create-form", views.create_form, name='create-form'),
    path("update-form/<int:room_id>", views.updateRoom, name='update-form'),
    path("delete-form/<int:room_id>", views.deleteRoom, name='delete-room'),
    path('delete-message/<int:message_id>', views.deleteMessage,
         name='delete-message'),
    path('user-profile/<int:user_id>', views.userProfile, name='user-profile'),
    path('edit-user', views.updateUser, name='edit-user'),
    path('topics/', views.topicsPage, name='topics'),
    path('activity/', views.activityPage, name='activity'),
    
]

studybuddy/urls.py
from django.urls import include, path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('api/', include('base.api.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/models.py
from email.policy import default
from django.db import models
from django.contrib.auth.models import AbstractUser
import os
import base64
from studybuddy import settings
# Create your models here.

# creating our own User Model that inherits all the functionality of
# inbuilt User Model


def image_as_base64(image_file, format='png'):
    """
    :param `image_file` for the complete path of image.
    :param `format` is format for image, eg: `png` or `jpg`.
    """
    print("img path ", image_file)
    if not os.path.isfile(image_file):
        return None

    encoded_string = ''
    with open(image_file, 'rb') as img_f:
        encoded_string = base64.b64encode(img_f.read())
    return 'data:image/%s;base64,%s' % (format, encoded_string.decode())


class User(AbstractUser):
    name = models.CharField(max_length=200, null=True)
    email = models.EmailField(unique=True, null=True)
    bio = models.TextField(null=True)
    # Note : Django ImageField in models relies on pillow library to process
    # the image. So make sure it is installed.
    # Also set the MEDIA_ROOT and MEDIA_URL in main app settings.
    avatar = models.ImageField(null=True, default="avatar.svg")
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def get_avatar_base64(self):
        # settings.MEDIA_ROOT = '/path/to/env/projectname/media'
        return image_as_base64(self.avatar.path)


class Topic(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Room(models.Model):
    host = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    # models.SET_NULl will set topic field to null if
    # topic object gets deleted.
    topic = models.ForeignKey(Topic, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    participants = models.ManyToManyField(User,
                                          related_name="participants",
                                          blank=True)
    # auto_now = True means  the field will be updated every time there is
    # a change in model
    updated = models.DateTimeField(auto_now=True)
    # auto_now_add=True means the field will be updated only first time
    # when we make changes to our models
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        # This will orderBy descending order of updated and created
        # without "-" will order it in ascending order
        ordering = ['-updated', '-created']

    def __str__(self):
        return self.name


class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,related_name="messages")
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    body = models.TextField()
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        # This will orderBy descending order of updated and created
        # without "-" will order it in ascending order
        ordering = ['-updated', '-created']

    def __str__(self):
        return self.body

base/forms.py
from dataclasses import fields
from django.forms import ModelForm
from .models import Room, Message, User
from django.contrib.auth.forms import UserCreationForm


class MyUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['name', 'username', 'email', 'password1', 'password2']


class RoomForm(ModelForm):
    class Meta:
        model = Room
        fields = '__all__'
        exclude = ['host', 'participants']


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['avatar', 'name', 'bio', 'username', 'email']

base/api/views.py
from pickle import GET
from django.http import JsonResponse
from rest_framework.decorators import api_view
from rest_framework.response import Response
from base.models import Room
from .serializers import RoomSerializer


@api_view(['GET'])
def getRoutes(request):
    routes = [
        'GET /api',
        'GET /api/rooms',
        'GET /api/rooms/:id'
    ]
    # safe=False basically means that the argument that is passed to
    # JsonResponse doesn't have to be a dictionary
    return Response(routes)


@api_view(['GET'])
def getRooms(request):
    rooms = Room.objects.all()
    # many=True is because we are passing QuerySet
    serializer = RoomSerializer(rooms, many=True)
    return Response(serializer.data)


@api_view(['GET'])
def getRoom(request, room_id):
    room = Room.objects.get(pk=room_id)
    # many=False is because we are passing one object and expecting one Json object
    serializer = RoomSerializer(room, many=False)
    return Response(serializer.data)

base/views.py
from ast import operator
from multiprocessing import context
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.db.models import Q
from numpy import require
from pyparsing import Or
from requests import RequestException, session
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .models import Message, Room, Topic, User
from .forms import RoomForm, Message, UserForm, MyUserCreationForm


def loginUser(request):
    page = 'login'
    context = {'page': page}
    if request.user.is_authenticated:
        return redirect('base:home')
    if request.method == 'POST':
        email = request.POST.get('email').lower()
        password = request.POST.get('password')

        try:
            user = User.objects.get(email=email)
        except:
            # message will help us to throw flash messages( It will
            # disappear after 1 refresh)
            messages.error(request, "User doesn't exist.")
        user = authenticate(request, email=email, password=password)
        if user is not None:
            # login() function will create a session in user browser
            # as well as in our database
            login(request, user)
            return redirect('base:home')
        else:
            messages.error(request, "User or Password doesn't exist.")

    return render(request, 'base/login_register.html', context)


def logoutUser(request):
    # logout(request) will delete the token so the user will not be in
    # session
    logout(request)
    return redirect('base:home')


def registerUser(request):
    form = MyUserCreationForm()
    context = {
        'form': form
    }
    if request.method == 'POST':
        # creates an instance of form with data populated by request.POST
        form = MyUserCreationForm(request.POST)
        if form.is_valid():
            print('the form is valid while regestring')
            # before actually saving the object in the database. if we want to make
            # changes to our object. We can get the object using form.save(commit=False)
            # form.save(commit=False) will throw an object of model which we want to save
            # in our database.
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()
            login(request, user)
            context['username'] = user.username
            return redirect('base:home')
        else:
            print(form.errors)
    return render(request, 'base/login_register.html', context)


def home(request):
    q = request.GET.get('q') if request.GET.get('q') else ''
    room_messages = Message.objects.filter(Q(room__topic__name__icontains=q))
    # using "Q" we can lookup using "|"(or)
    # operator
    rooms = Room.objects.filter(Q(topic__name__icontains=q) |
                                Q(name__icontains=q) |
                                Q(description__icontains=q) |
                                Q(host__username__icontains=q))
    topics = Topic.objects.all()[0:5]
    # use count instead of len() to count the number of items in
    # querySet because count is much faster than len
    context = {
        'rooms': rooms,
        'topics': topics,
        'total_rooms': rooms.count(),
        'room_messages': room_messages,
    }
    return render(request, 'base/home.html', context)

@login_required(login_url='base:login')
def room(request, room_id):
    room = Room.objects.get(pk=room_id)
    room_messages = room.message_set.all().order_by('-created')
    participants = room.participants.all()
    context = {
        'room': room,
        'room_messages': room_messages,
        'participants': participants,
    }
    if request.method == "POST":
        # objects.create() will create the object and save it to database in a single step
        # so instead of using .save() method after creating the instance we can use this
        print("Post called")
        print("message ", request.POST['body'])
        message = Message.objects.create(
            user=request.user,
            room=room,
            body=request.POST['body']
        )
        print(message)
        room.participants.add(message.user)
        return redirect('base:room', room_id)
    return render(request, 'base/room.html', context)

# CREATE


@login_required(login_url='base:login')
# this login_required decorator add some functionality to our
# create_form view. Only the user who are currently in the session are
# allowed to create form . if the user is not in the session it will
# redirect to whatever url we pass with login_url
def create_form(request):
    form = RoomForm()
    topics = Topic.objects.all()
    if request.method == 'POST':
        # this will create a form instance with data populated by request.POST
        # form = RoomForm(request.POST)

        topic_name = request.POST['topic']
        # this will bascially check if the object of this specific field is present or not
        # if it is present then create will be False and it will return
        # the present object. And if the object is not present then it will create
        # a new object and in this case create will be True.
        topic, create = Topic.objects.get_or_create(name=topic_name)
        Room.objects.create(
            host=request.user,
            topic=topic,
            name=request.POST['name'],
            description=request.POST['description']
        )
        return redirect('base:home')
    context = {
        'form': form,
        'topics': topics,
    }
    return render(request, 'base/room_form.html', context)

# UPDATE


@login_required(login_url='base:login')
def updateRoom(request, room_id):
    room = Room.objects.get(pk=room_id)
    # we are allowing only the host of the room to update/delete the
    # room and not any user who has logged in
    if request.user != room.host:
        return HttpResponse("You are not allowed here.")
    # here instance=room will create a form which will be filled
    # with all the fields of the object room
    form = RoomForm(instance=room)  # pre filling form
    context = {'form': form, 'room': room}
    if request.method == 'POST':
        # make sure to pass the object( instance=room) or else
        # instead of updating it will create a new object in db
        # form = RoomForm(request.POST, instance=room)
        topic_name = request.POST['topic']
        # this will bascially check if the object of this specific field is present or not
        # if it is present then create will be False and it will return
        # the present object. And if the object is not present then it will create
        # a new object and in this case create will be True.
        topic, create = Topic.objects.get_or_create(name=topic_name)
        room.topic = topic
        room.name = request.POST['name']
        room.description = request.POST['description']
        room.save()
        return redirect('base:home')
    return render(request, 'base/room_form.html', context)

# DELETE


@login_required(login_url='base:login')
def deleteRoom(request, room_id):
    room = Room.objects.get(pk=room_id)
    # we are allowing only the host of the room to update/delete the
    # room and not any user who has logged in
    if request.user != room.host:
        return HttpResponse("You are not allowed here.")
    if request.method == "POST":
        room.delete()
        return redirect('base:home')
    return render(request, 'base/deleteItem.html', {"obj": room})


@login_required(login_url='base:login')
def deleteMessage(request, message_id):
    message = Message.objects.get(pk=message_id)
    # we are allowing only the host of the room to update/delete the
    # room and not any user who has logged in
    if request.user != message.user:
        return HttpResponse("You are not allowed here.")
    if request.method == "POST":
        message.delete()
        return redirect('base:home')
    return render(request, 'base/deleteItem.html', {"obj": message})


def userProfile(request, user_id):
    user = User.objects.get(pk=user_id)
    rooms = user.room_set.all()
    topics = Topic.objects.all()
    room_messages = user.messages.all()
    context = {
        'user': user,
        'rooms': rooms,
        'topics': topics,
        'room_messages': room_messages
    }
    return render(request, 'base/user_profile.html', context)


@login_required(login_url='base:login')
def updateUser(request):
    user = request.user
    form = UserForm(instance=user)  # pre filling
    context = {
        'form': form}
    if request.method == "POST":
        form = UserForm(request.POST, request.FILES, instance=user)
        form.save()
        return redirect("base:user-profile", user.id)
    return render(request, 'base/edit-user.html', context)


def topicsPage(request):
    q = request.GET.get('q') if request.GET.get('q') else ''
    topics = Topic.objects.filter(name__icontains=q)
    return render(request, 'base/topics.html', {'topics': topics})


def activityPage(request):
    room_messages = Message.objects.all()
    return render(request, 'base/activity.html', {'room_messages': room_messages})

base/templates/base/home.html
{% extends 'main.html' %}
{% block content %}
    <main class="layout layout--3">
      <div class="container">
        <!-- Topics Start -->
         {% include 'base/topics_component.html' %}
        <!-- Topics End -->
        <!-- Room List Start -->
        <div class="roomList">
          <div class="mobile-menu">
            <form class="header__search" action="{% url 'base:home' %}" method="GET">
              <label>
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>search</title>
                  <path
                    d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
                  ></path>
                </svg>
                <input name="q" placeholder="Search for posts" />
              </label>
            </form>
            <div class="mobile-menuItems">
              <a class="btn btn--main btn--pill" href="{% url 'base:topics' %}">Browse Topics</a>
              <a class="btn btn--main btn--pill" href="{% url 'base:activity' %}">Recent Activities</a>
            </div>
          </div>
          <div class="roomList__header">
            <div>
              <h2>Study Room</h2>
              <p> {{ total_rooms }} available</p>
            </div>
            <a class="btn btn--main" href="{% url 'base:create-form' %}">
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>add</title>
                <path
                  d="M16.943 0.943h-1.885v14.115h-14.115v1.885h14.115v14.115h1.885v-14.115h14.115v-1.885h-14.115v-14.115z"
                ></path>
              </svg>
              Create Room
            </a>
          </div>
            {% include 'base/feed_component.html' %}
        </div>
        <!-- Room List End -->

        {% include 'base/recent_activities_component.html' %}
    
        <!-- Activities End -->
      </div>
    </main>

{% endblock %}

base/templates/base/login_register.html
{% extends 'main.html' %} 
{% block content %} 
{% if page == 'login' %}
<main class="auth layout">
  <div class="container">
    <div class="layout__box">
      <div class="layout__boxHeader">
        <div class="layout__boxTitle">
          <h3>Login</h3>
        </div>
      </div>
      <div class="layout__body">
        <h2 class="auth__tagline">Find your study partner</h2>

        <form class="form" action="" method="POST">
          {% csrf_token %}
          <div class="form__group form__group">
            <label for="room_name">Email</label>
            <input
              id="username"
              name="email"
              type="text"
              placeholder="e.g. dennis_ivy"
            />
          </div>
          <div class="form__group">
            <label for="password">Password</label>
            <input
              id="password"
              name="password"
              type="password"
              placeholder="&bull;&bull;&bull;&bull;&bull;&bull;&bull;&bull;"
            />
          </div>

          <button class="btn btn--main" type="submit">
            <svg
              version="1.1"
              xmlns="http://www.w3.org/2000/svg"
              width="32"
              height="32"
              viewBox="0 0 32 32"
            >
              <title>lock</title>
              <path
                d="M27 12h-1v-2c0-5.514-4.486-10-10-10s-10 4.486-10 10v2h-1c-0.553 0-1 0.447-1 1v18c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-18c0-0.553-0.447-1-1-1zM8 10c0-4.411 3.589-8 8-8s8 3.589 8 8v2h-16v-2zM26 30h-20v-16h20v16z"
              ></path>
              <path
                d="M15 21.694v4.306h2v-4.306c0.587-0.348 1-0.961 1-1.694 0-1.105-0.895-2-2-2s-2 0.895-2 2c0 0.732 0.413 1.345 1 1.694z"
              ></path>
            </svg>

            Login
          </button>
        </form>

        <div class="auth__action">
          <p>Haven't signed up yet?</p>
          <a href="{% url 'base:register' %}" class="btn btn--link">Sign Up</a>
        </div>
      </div>
    </div>
  </div>
</main>
{% else %}
<main class="auth layout">
  <div class="container">
    <div class="layout__box">
      <div class="layout__boxHeader">
        <div class="layout__boxTitle">
          <h3>Register</h3>
        </div>
      </div>
      <div class="layout__body">
        <h2 class="auth__tagline">Find your study partner</h2>

        <form class="form" action="" method="POST">
          {% csrf_token %}
          {% for field in form %}
          <div class="form__group form__group">
            <label for="room_name">{{field.label}}</label>
            {{ field }}
          </div>
          {% endfor %}
          <button class="btn btn--main" type="submit">
            <svg
              version="1.1"
              xmlns="http://www.w3.org/2000/svg"
              width="32"
              height="32"
              viewBox="0 0 32 32"
            >
              <title>lock</title>
              <path
                d="M27 12h-1v-2c0-5.514-4.486-10-10-10s-10 4.486-10 10v2h-1c-0.553 0-1 0.447-1 1v18c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-18c0-0.553-0.447-1-1-1zM8 10c0-4.411 3.589-8 8-8s8 3.589 8 8v2h-16v-2zM26 30h-20v-16h20v16z"
              ></path>
              <path
                d="M15 21.694v4.306h2v-4.306c0.587-0.348 1-0.961 1-1.694 0-1.105-0.895-2-2-2s-2 0.895-2 2c0 0.732 0.413 1.345 1 1.694z"
              ></path>
            </svg>
            Register
          </button>
        </form>

        <div class="auth__action">
          <p>Already Signed up ?</p>
          <a href="{% url 'base:login' %}" class="btn btn--link">Sign In</a>
        </div>
      </div>
    </div>
  </div>
</main>
{% endif %} 
{% endblock %}

base/templates/base/login_register_old.html
{% extends 'main.html' %} {% block content %}

{% if page == 'login' %}
<div>
  <form method="POST" action="">
    {% csrf_token %}
    <label>Username</label>
    <input type="username" name="username" placeholder="Enter Username..." />
    <label>Password</label>
    <input type="password" name="password" placeholder="Enter Password..." />
    <input type="submit" name="Login" />
    <h3>Haven't Signed up yet?
      <a href="{% url 'base:register' %}"> Sign up </a>
    </h3>
  </form>
</div>
{% else %}
<div>
  <form method="POST" action="">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" name="Login" />
    <h3>Already Signed in ?
      <a href="{% url 'base:login' %}"> Log in </a>
    </h3>
  </form>
</div>
{% endif %}
{% endblock %}

base/templates/base/room.html
{% extends 'main.html' %} {% block content %}
<main class="profile-page layout layout--2">
  <div class="container">
    <!-- Room Start -->
    <div class="room">
      <div class="room__top">
        <div class="room__topLeft">
          <a href="{% url 'base:home' %}">
            <svg
              version="1.1"
              xmlns="http://www.w3.org/2000/svg"
              width="32"
              height="32"
              viewBox="0 0 32 32"
            >
              <title>arrow-left</title>
              <path
                d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
              ></path>
            </svg>
          </a>
          <h3>Study Room</h3>
        </div>
        {% if room.host == request.user %}
        <div class="room__topRight">
          <a href="{% url 'base:update-form' room.id %}">
            <svg
              enable-background="new 0 0 24 24"
              height="32"
              viewBox="0 0 24 24"
              width="32"
              xmlns="http://www.w3.org/2000/svg"
            >
              <title>edit</title>
              <g>
                <path
                  d="m23.5 22h-15c-.276 0-.5-.224-.5-.5s.224-.5.5-.5h15c.276 0 .5.224.5.5s-.224.5-.5.5z"
                />
              </g>
              <g>
                <g>
                  <path
                    d="m2.5 22c-.131 0-.259-.052-.354-.146-.123-.123-.173-.3-.133-.468l1.09-4.625c.021-.09.067-.173.133-.239l14.143-14.143c.565-.566 1.554-.566 2.121 0l2.121 2.121c.283.283.439.66.439 1.061s-.156.778-.439 1.061l-14.142 14.141c-.065.066-.148.112-.239.133l-4.625 1.09c-.038.01-.077.014-.115.014zm1.544-4.873-.872 3.7 3.7-.872 14.042-14.041c.095-.095.146-.22.146-.354 0-.133-.052-.259-.146-.354l-2.121-2.121c-.19-.189-.518-.189-.707 0zm3.081 3.283h.01z"
                  />
                </g>
                <g>
                  <path
                    d="m17.889 10.146c-.128 0-.256-.049-.354-.146l-3.535-3.536c-.195-.195-.195-.512 0-.707s.512-.195.707 0l3.536 3.536c.195.195.195.512 0 .707-.098.098-.226.146-.354.146z"
                  />
                </g>
              </g>
            </svg>
          </a>
          <a href="{% url 'base:delete-room' room.id %}">
            <svg
              version="1.1"
              xmlns="http://www.w3.org/2000/svg"
              width="32"
              height="32"
              viewBox="0 0 32 32"
            >
              <title>remove</title>
              <path
                d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
              ></path>
            </svg>
          </a>
        </div>
        {% endif %}
      </div>
      <div class="room__box scroll">
        <div class="room__header scroll">
          <div class="room__info">
            <h3>{{ room.name }}</h3>
            <span>{{ room.created | timesince }}</span>
          </div>
          <div class="room__hosted">
            <p>Hosted By</p>
            <a href="#" class="room__author">
              <div class="avatar avatar--small">
                <img src="{{ room.host.avatar.url }}" />
              </div>
              <span>@{{ room.host.username }}</span>
            </a>
          </div>
          {% comment %}
          <div class="room__details">
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quasi,
            tenetur laudantium? Dicta repellendus rerum consectetur, voluptatem
            repudiandae eum ea porro cupiditate provident nulla, deserunt, ab
            ipsum corporis laboriosam deleniti molestias?
          </div>
          {% endcomment %}
          <span class="room__topics">{{ room.topic }}</span>
        </div>
        <div class="room__conversation">
          <div id="threads-scroll" class="threads scroll">
            {% for message in room_messages %}
            <div class="thread">
              <div class="thread__top">
                <div class="thread__author">
                  <a
                    href="{% url 'base:user-profile' message.user.id %}"
                    class="thread__authorInfo"
                  >
                    <div class="avatar avatar--small">
                      <img src="{{ message.user.avatar.url }}" />
                    </div>
                    <span>@{{ message.user.username }}</span>
                  </a>
                  {% if message.created|timesince > '1 minutes' %}
                  <span class="thread__date"
                    >{{ message.created|timesince }}</span
                  >
                  {% else %}
                  <span class="thread__date">Just now</span>
                  {% endif %}
                </div>
                {% if request.user == message.user %}
                <a href="{% url 'base:delete-message' message.id %}">
                  <div class="thread__delete">
                    <svg
                      version="1.1"
                      xmlns="http://www.w3.org/2000/svg"
                      width="32"
                      height="32"
                      viewBox="0 0 32 32"
                    >
                      <title>remove</title>
                      <path
                        d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
                      ></path>
                    </svg>
                  </div>
                </a>
                {% endif %}
              </div>
              <div class="thread__details">{{ message.body }}</div>
            </div>
            {% endfor %}
          </div>
        </div>
      </div>
      <div class="room__message">
        <form id="form" action="" method="POST">
          {% csrf_token %}
          <input
            id="chat-input"
            name="body"
            placeholder="Write your message here..."
          />
        </form>
      </div>
    </div>
    <!-- Room End -->

    <!--   Start -->
    <div class="participants">
      <h3 class="participants__top">
        Participants <span>{{ participants.count }}</span>
      </h3>
      <div class="participants__list scroll">
        {% for user in participants %}
        <a href="{% url 'base:user-profile' user.id %}" class="participant">
          <div class="avatar avatar--medium">
            <img src="{{ user.avatar.url }}" />
          </div>
          <p>
            {{ user.username }}
            <span>@{{ user.username }}</span>
          </p>
        </a>
        {% endfor %}
      </div>
    </div>
    <!--  End -->
  </div>
</main>
{{room.id|json_script:"room_id"}}
{{request.user.username|json_script:"username"}}
<script type="text/javascript">
  const roomId = JSON.parse(document.getElementById("room_id").textContent);
  const username = JSON.parse(document.getElementById("username").textContent);
  const chatSocket = new WebSocket(
    `ws://${window.location.host}/ws/chat/${roomId}/`
  );
  chatSocket.onmessage = function (e) {
    const data = JSON.parse(e.data);
    console.log(data)
    avatar_b64 = data["avatar_b64"]
    const img = new Image();
    img.src = avatar_b64;

    document.getElementById(
      "threads-scroll"
    ).innerHTML = `<div class="thread">
              <div class="thread__top">
                <div class="thread__author">
                  <a
                    href="#"
                    class="thread__authorInfo"
                  >
                    <div class="avatar avatar--small">
                      <img src="${img.src}" />
                    </div>
                    <span>@${data.username}</span>
                  </a>
                  <span class="thread__date"
                    >Just now </span
                  >
                </div>
                {% if request.user.username == data.username %}
                <a href="#">
                  <div class="thread__delete">
                    <svg
                      version="1.1"
                      xmlns="http://www.w3.org/2000/svg"
                      width="32"
                      height="32"
                      viewBox="0 0 32 32"
                    >
                      <title>remove</title>
                      <path
                        d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
                      ></path>
                    </svg>
                  </div>
                </a>
                {% endif %}
              </div>
              <div class="thread__details">${data.message}</div>
            </div>` + document.getElementById(
      "threads-scroll"
    ).innerHTML;
  };
  function helper(e) {
    const chatText = document.getElementById("chat-input");
    const message = chatText.value;
    console.log(message);
    chatSocket.send(
      JSON.stringify({
        message: message,
        username: username,
      })
    );
  }
  function handler(e) {
    if (e.key === "Enter") {
      helper(e);
    }
  }
  function handlerClick(e) {
    helper(e);
  }
  {% comment %} document.getElementById("chat-input").addEventListener("keydown", handler); {% endcomment %}
  document.getElementById("form").addEventListener("submit", handlerClick);
</script>
{% endblock %}